version: '3.9'

services:
  order:
    build:
      context: ./services/order/
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./utils/database_manager.py
        target: /app/utils/database_manager.py
      - type: bind
        source: ./utils/logger.py
        target: /app/utils/logger.py
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_started
      kafka-topics-setup:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy

  payment:
    build:
      context: ./services/payment/
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./utils/database_manager.py
        target: /app/utils/database_manager.py
      - type: bind
        source: ./utils/logger.py
        target: /app/utils/logger.py
    env_file:
      - ./.env
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_started
      kafka-topics-setup:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy

  inventory:
    build:
      context: ./services/inventory/
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./utils/database_manager.py
        target: /app/utils/database_manager.py
      - type: bind
        source: ./utils/logger.py
        target: /app/utils/logger.py
    env_file:
      - ./.env
    ports:
      - "8002:8000"
    depends_on:
      postgres:
        condition: service_started
      kafka-topics-setup:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    container_name: ${POSTGRES_HOST}
    restart: unless-stopped
    ports:
      - 5433:${POSTGRES_PORT}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./services/db_init_scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} && psql --username=${POSTGRES_USER} --list"
      interval: 5s
      timeout: 1s
      retries: 15
      start_period: 5s

  kafka:
    image: bitnami/kafka:4.0.0
    container_name: kafka
    ports:
      - "9092:9092"    # Internal PLAINTEXT
      - "9093:9093"    # Controller
      - "29092:29092"  # External
    environment:
      - BITNAMI_DEBUG=true
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_LOG_DIRS=/bitnami/kafka/data
      - CLUSTER_ID=abcdefghijklmnopqrstuv
    volumes:
      - kafka_data:/bitnami/kafka/data
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 5s
      retries: 10

  kafka-topics-setup:
    image: bitnami/kafka:4.0.0
    container_name: kafka-topics-setup
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_CFG_BOOTSTRAP_SERVERS=kafka:9092
    command: >
      bash -c "
        echo 'Waiting for Kafka to be ready...';
        cub kafka-ready -b kafka:9092 1 30;
        echo 'Creating topics...';
        kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic order_created --partitions 3 --replication-factor 1;
        kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic payment_initiated --partitions 3 --replication-factor 1;
        echo 'Topics created successfully';
      "
    restart: on-failure

volumes:
  postgres_data:
  kafka_data:
